try:
    from weasyprint import HTML
    WEASYPRINT_AVAILABLE = True
except OSError:
    WEASYPRINT_AVAILABLE = False
    print("WARNING: WeasyPrint system dependencies not found. PDF generation will be mocked.")

from app.models.schemas import UserProfile
from app.rules.deductions import analyze_tax_situation
import io

def generate_pdf_plan(profile: UserProfile) -> bytes:
    """
    Generates a PDF tax plan for the user.
    """
    if not WEASYPRINT_AVAILABLE:
        return b"%PDF-1.4 Mock PDF Content for Demo"

    analysis = analyze_tax_situation(profile)
    
    # Simple HTML Template
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: sans-serif; padding: 40px; }}
            h1 {{ color: #2563eb; }}
            h2 {{ color: #1e40af; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; margin-top: 30px; }}
            .summary-box {{ background: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0; }}
            .stat {{ display: flex; justify-content: space-between; margin: 10px 0; font-size: 16px; }}
            .highlight {{ font-weight: bold; color: #16a34a; }}
            .disclaimer {{ margin-top: 50px; font-size: 12px; color: #6b7280; text-align: center; }}
        </style>
    </head>
    <body>
        <h1>TaxNova Optimization Plan</h1>
        <p><strong>Job ID:</strong> {profile.job_id}</p>
        <p><strong>Date:</strong> 2024-11-27</p>
        
        <h2>Key Observations</h2>
        <ul>
            {''.join([f"<li><strong>{obs['title']}</strong> ({obs['impact']}): {obs['description']}</li>" for obs in profile.observations])}
        </ul>

        <h2>Recommended Actions</h2>
        <ul>
            {''.join([f"<li><strong>{rec.title}</strong>: {rec.description} (Save ~₹{rec.estimated_tax_savings:,})</li>" for rec in profile.recommendations])}
        </ul>
        
        <h2>Tax Calculation Summary</h2>
        <div class="summary-box">
            <div class="stat">
                <span>Gross Salary:</span>
                <span>₹{profile.parsed_payroll.gross_salary:,}</span>
            </div>
            <div class="stat">
                <span>Taxable Income (Old Regime):</span>
                <span>₹{profile.parsed_payroll.gross_salary - analysis.get('hra_exempt', 0) - 50000 - analysis.get('util_80c', 0) - profile.health_premium:,}</span>
            </div>
             <div class="stat">
                <span>Tax Liability (Old Regime):</span>
                <span>₹{analysis.get('tax_old', 0):,}</span>
            </div>
             <div class="stat">
                <span>Tax Liability (New Regime):</span>
                <span>₹{analysis.get('tax_new', 0):,}</span>
            </div>
        </div>
        
        <h2>Next Steps</h2>
        <ol>
            <li>Submit rent receipts to your employer.</li>
            <li>Invest remaining 80C amount before March 31st.</li>
            <li>File ITR-1 in July.</li>
        </ol>

        <div class="disclaimer">
            <p>Disclaimer: This report is generated by an AI agent. Please consult a qualified CA before filing taxes.</p>
        </div>
    </body>
    </html>
    """
    
    pdf_file = io.BytesIO()
    try:
        HTML(string=html_content).write_pdf(pdf_file)
    except Exception as e:
        print(f"Error generating PDF: {e}")
        return b"%PDF-1.4 Mock PDF Content (Generation Failed)"
        
    pdf_file.seek(0)
    return pdf_file.read()
